openapi: 3.0.0

info:
  title: Mis Dulzuras en el Mar.
  version: 1.0.0
paths:
  /carts:
    get:
      summary: Obtenemos todos los carritos de la BD
      tags:
        - carts
      responses:
        "200":
          description: Obtienen todos los carritos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/carts"
        "500":
          description: Error interno del servidor
components:
  schemas:
    product:
      type: object
      properties:
        _id:
          type: string
          description: Id autogenerado por MongoDB
        products:
          type: string
          description: descripción del producto en carrito        
      example:
        description: torta
        price: 210
        code: aaa124
        
